### ISSUE TITLE
gather_height breaks when HeightLowerHerb column is all NA

### ISSUE THREAD

**Issue by annack84** [Landscape-Data-Commons/terradactyl#165]
Seems to be a problem in the gather_height_terradat() method. The step to create the nas_by_coercion object gives the following error on my data:

Error in `vec_assign()`:
! Can't convert `replace` <character> to match type of `data` <logical>.

I think this is because the HeightLowerHerb column in my data is all NA values. When I run class(detail$HeightLowerHerb), the result is "logical".

I think this might fix the problem:

as.character(detail[[paste0("Height", X)]]) |> tidyr::replace_na(data = _,
                   replace = "placeholder") |>
     as.numeric() |>
     suppressWarnings() |>
     is.na() |>
     sum()

**Comment by annack84** [comment]
Additional info: I used  terradactylUtils::dima_prep to pull in tblLPIHeader from a DIMA database that I successfully processed with terradactyl on 6/6/2023. 

Also, the solution I suggested in my initial comment resolves the "Error in vec_assign()" problem, but a new problem shows up in the next section, because the step to create the lpi_heights_tall object gives this error:

Error in `dplyr::bind_rows()`:
! Can't combine `..1$Species` <character> and `..3$Species` <logical>.

I can resolve both errors by manually setting the class of tblLPIDetail$SpeciesLowerHerb and tblLPIDetail$HeightLowerHerb in my input data to "character", but it adds a step to a workflow that didn't used to need it, and the solution isn't easy to find with the current error messages.

**Comment by nstauffer** [comment]
Thanks for the report and the possible fix! I've just pushed a patch. The solution to keep it as simple as possible (and make it simpler than before) was this:

```
current_na_count <- sum(is.na(detail[[paste0("Height", X)]]))
coerced_na_count <- sum(is.na(as.numeric(detail[[paste0("Height", X)]]))) - current_na_count
```

**Comment by annack84** [comment]
Still having trouble related to this after the update, unfortunately.

height_tall <- gather_height(source = "DIMA",
                             tblLPIHeader = l_dima_tables$tblLPIHeader,
                              tblLPIDetail = l_dima_tables$tblLPIDetail)
Error in `dplyr::bind_rows()`:
! Can't combine `..1$Species` <logical> and `..2$Species` <character>.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/vctrs_error_ptype2>
Error in `dplyr::bind_rows()`:
! Can't combine `..1$Species` <logical> and `..2$Species` <character>.
---
Backtrace:
    ▆
 1. └─terradactyl::gather_height(...)
 2.   └─terradactyl::gather_height_terradat(...)
 3.     └─dplyr::bind_rows(...)

Some more details about the data I'm using:

class(l_dima_tables$tblLPIDetail$SpeciesHerbaceous)
[1] "character"
> class(l_dima_tables$tblLPIDetail$SpeciesWoody)
[1] "logical"
> class(l_dima_tables$tblLPIDetail$SpeciesLowerHerb)
[1] "logical"
> head(l_dima_tables$tblLPIDetail$SpeciesHerbaceous)
[1] "" "" "" "" "" ""
> head(l_dima_tables$tblLPIDetail$SpeciesWoody)
[1] NA NA NA NA NA NA
> head(l_dima_tables$tblLPIDetail$SpeciesLowerHerb)
[1] NA NA NA NA NA NA

The only one of those columns containing real data is SpeciesHerbaceous. If I force Species Woody and SpeciesLowerHerb to be empty character columns instead of empty logical columns, gather_height works as expected. I did remove and reinstall terradactyl before running this, so I think I should have gotten the patch pushed on 12/13/24

**Comment by annack84** [comment]
I'm still having the same problem I commented on in January - getting an error message when I try to run gather_height on DIMA data:

height_tall <- gather_height(source = "DIMA",
                             tblLPIHeader = l_dima_tables$tblLPIHeader,
                             tblLPIDetail = l_dima_tables$tblLPIDetail)

Error in `dplyr::bind_rows()`:
! Can't combine `..1$Species` <character> and `..3$Species` <logical>.

My current workaround is to run these two lines before running gather_height:
l_dima_tables$tblLPIDetail$SpeciesLowerHerb <- as.character(l_dima_tables$tblLPIDetail$SpeciesLowerHerb)
l_dima_tables$tblLPIDetail$SpeciesWoody <- as.character(l_dima_tables$tblLPIDetail$SpeciesWoody)

**Comment by nstauffer** [comment]
Thanks for pointing out that it's not just heights that this can happen with in a data set. The next patch should cover a wider (hopefully the entire) range of possible empty variables that produce class mismatches.

**Comment by nstauffer** [comment]
This should be patched now in the main branch, although a new version release number hasn't been set yet.

The handling is slightly different now, notifying the user if variables are of an unexpected class (e.g., no values in SpeciesLowerHerb resulting in the class being logical instead of character) that will be coerced and then following up with additional warnings regarding NAs introduced by coercion as necessary.
